# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento_trabalho1', '0002_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Publicacao',
        ),
    ]
